mode: immediate
branchName: ${issue.number}
branches:
  - label: AN
    name: an/dev
    prefix: an/feat/
autoLinkIssue: true
autoCloseIssue: true
openPR: false
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
