name: Android CI Pipeline

on:
  push:
    branches:
      - main
      - an/**
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

env:
  API_KEY: ${{ secrets.API_KEY }}
  BASE_URL_DEV: ${{ secrets.BASE_URL_DEV }}
  BASE_URL_API: ${{ secrets.BASE_URL_API }}
  TABLE_NAME: ${{ secrets.TABLE_NAME }}

jobs:
  ktlint_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variable for BuildConfig
        run: |
          echo api_key=\"$API_KEY\" > ./local.properties
          echo base_url_dev=\"$BASE_URL_DEV\" >> ./local.properties
          echo base_url_release=\"$BASE_URL_API\" >> ./local.properties
          echo table_name=\"$TABLE_NAME\" >> ./local.properties

      - name: Cache Gradle Home
        uses: actions/cache@v3.1.0
        with:
          path: ~/.gradle
          key: gradle-home-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-home-${{ runner.os }}-

      - name: Verify Gradle Cache Integrity
        run: ls -lah ~/.gradle || echo "Gradle cache not found."

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Verify Gradle Wrapper Version
        run: ./gradlew --version

      - name: Verify Gradle Wrapper Integrity
        run: ./gradlew wrapper --gradle-version

      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-daemon

  build_test:
    runs-on: ubuntu-latest
    needs: ktlint_check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variable for BuildConfig
        run: |
          echo api_key=\"$API_KEY\" > ./local.properties
          echo base_url_dev=\"$BASE_URL_DEV\" >> ./local.properties
          echo base_url_release=\"$BASE_URL_API\" >> ./local.properties
          echo table_name=\"$TABLE_NAME\" >> ./local.properties

      - name: Cache Gradle Home
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-home-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-home-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Verify Gradle Wrapper Version
        run: ./gradlew --version

      - name: Build and Test
        run: ./gradlew build test
