name: Android CI Pipeline

on:
  push:
    branches:
      - main
      - an/**
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

env:
  API_KEY: ${{ secrets.API_KEY }}
  BASE_URL_DEV: ${{ secrets.BASE_URL_DEV }}
  BASE_URL_API: ${{ secrets.BASE_URL_API }}
  TABLE_NAME: ${{ secrets.TABLE_NAME }}

jobs:
  ktlint_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variable for BuildConfig
        run: |
          echo "api_key=${{ secrets.API_KEY }}" > local.properties
          echo "base_url_dev=${{ secrets.BASE_URL_DEV }}" >> local.properties
          echo "base_url_release=${{ secrets.BASE_URL_API }}" >> local.properties
          echo "table_name=${{ secrets.TABLE_NAME }}" >> local.properties
          cat local.properties

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/jars-3
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-daemon

  build_test:
    runs-on: ubuntu-latest
    needs: ktlint_check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variables
        run: |
          echo "api_key=${{ secrets.API_KEY }}" > local.properties
          echo "base_url_dev=${{ secrets.BASE_URL_DEV }}" >> local.properties
          echo "base_url_release=${{ secrets.BASE_URL_API }}" >> local.properties
          echo "table_name=${{ secrets.TABLE_NAME }}" >> local.properties
          cat local.properties

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Configure Gradle Properties
        run: |
          echo "org.gradle.parallel=false" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx2g" >> gradle.properties

      - name: Build and Test
        run: ./gradlew build --info --stacktrace

      - name: Clean Gradle Cache if Build Fails
        if: failure()
        run: |
          ./gradlew --stop
          ./gradlew clean
          rm -rf ~/.gradle/caches/modules-2
          rm -rf ~/.gradle/caches/jars-3
